apiVersion: v1
kind: Service
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  ports:
    - port: 80
      nodePort: 32000
  selector:
    app: mydeploy
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  selector:
    matchLabels:
      app: mydeploy
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mydeploy
        tier: frontend
    spec:
      containers:
      - image: httpd
        name: mydeploy
        ports:
        - containerPort: 80
          name: mydeploy
        volumeMounts:
        - name: mydeploy-pvc-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: mydeploy-pvc-storage
        persistentVolumeClaim:
          claimName: mydeploy-pv-storage
